"""Changed the appointment relationship in the Prescription model

Revision ID: 3f604e637d36
Revises: 7bba444a2c30
Create Date: 2024-12-25 13:56:09.618982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f604e637d36'
down_revision: Union[str, None] = '7bba444a2c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
