"""Updated the doctor model with a unique constraint

Revision ID: 75a764eb5590
Revises: 771c12e1edcd
Create Date: 2024-12-23 16:23:21.098001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a764eb5590'
down_revision: Union[str, None] = '771c12e1edcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doctors_license_number', table_name='doctors')
    op.create_index(op.f('ix_doctors_license_number'), 'doctors', ['license_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctors_license_number'), table_name='doctors')
    op.create_index('ix_doctors_license_number', 'doctors', ['license_number'], unique=False)
    # ### end Alembic commands ###
