"""Added cascade delete to the appointment relationship in user and doctor

Revision ID: 7bba444a2c30
Revises: fbc9a477bd9d
Create Date: 2024-12-25 09:13:50.587918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bba444a2c30'
down_revision: Union[str, None] = 'fbc9a477bd9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
