"""Added CASCADING deletes to the models

Revision ID: b0f8a606fb92
Revises: 75a764eb5590
Create Date: 2024-12-23 20:19:50.796661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f8a606fb92'
down_revision: Union[str, None] = '75a764eb5590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_unique_constraint('uq_appointment_time', 'appointments', ['doctor_id', 'appointment_date', 'appointment_time'])
    op.drop_constraint('appointments_doctor_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_user_id_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('doctors_user_id_fkey', 'doctors', type_='foreignkey')
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_medical_records_doctor_id'), 'medical_records', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_medical_records_record_date'), 'medical_records', ['record_date'], unique=False)
    op.drop_constraint('medical_records_user_id_fkey', 'medical_records', type_='foreignkey')
    op.drop_constraint('medical_records_doctor_id_fkey', 'medical_records', type_='foreignkey')
    op.create_foreign_key(None, 'medical_records', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'medical_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_prescriptions_appointment_id'), 'prescriptions', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.drop_constraint('prescriptions_doctor_id_fkey', 'prescriptions', type_='foreignkey')
    op.drop_constraint('prescriptions_appointment_id_fkey', 'prescriptions', type_='foreignkey')
    op.create_foreign_key(None, 'prescriptions', 'appointments', ['appointment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'prescriptions', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_symptoms_appointment_id'), 'symptoms', ['appointment_id'], unique=False)
    op.drop_constraint('symptoms_appointment_id_fkey', 'symptoms', type_='foreignkey')
    op.drop_constraint('symptoms_user_id_fkey', 'symptoms', type_='foreignkey')
    op.create_foreign_key(None, 'symptoms', 'appointments', ['appointment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'symptoms', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'symptoms', type_='foreignkey')
    op.drop_constraint(None, 'symptoms', type_='foreignkey')
    op.create_foreign_key('symptoms_user_id_fkey', 'symptoms', 'users', ['user_id'], ['id'])
    op.create_foreign_key('symptoms_appointment_id_fkey', 'symptoms', 'appointments', ['appointment_id'], ['id'])
    op.drop_index(op.f('ix_symptoms_appointment_id'), table_name='symptoms')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.create_foreign_key('prescriptions_appointment_id_fkey', 'prescriptions', 'appointments', ['appointment_id'], ['id'])
    op.create_foreign_key('prescriptions_doctor_id_fkey', 'prescriptions', 'doctors', ['doctor_id'], ['id'])
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_appointment_id'), table_name='prescriptions')
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.create_foreign_key('medical_records_doctor_id_fkey', 'medical_records', 'doctors', ['doctor_id'], ['id'])
    op.create_foreign_key('medical_records_user_id_fkey', 'medical_records', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_medical_records_record_date'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_doctor_id'), table_name='medical_records')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_foreign_key('doctors_user_id_fkey', 'doctors', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_user_id_fkey', 'appointments', 'users', ['user_id'], ['id'])
    op.create_foreign_key('appointments_doctor_id_fkey', 'appointments', 'doctors', ['doctor_id'], ['id'])
    op.drop_constraint('uq_appointment_time', 'appointments', type_='unique')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    # ### end Alembic commands ###
