"""Fix foreign key on symptoms.appointment_id

Revision ID: c5719784bc80
Revises: 3f604e637d36
Create Date: 2024-12-26 13:56:00.761651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5719784bc80'
down_revision: Union[str, None] = '3f604e637d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
