"""Fix relationships in User and Doctor models

Revision ID: f53ead4d25d3
Revises: f2f159d79dea
Create Date: 2024-12-30 14:28:59.175107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53ead4d25d3'
down_revision: Union[str, None] = 'f2f159d79dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
