"""Remove doctor_username columns

Revision ID: fbc9a477bd9d
Revises: 80d4c5eb5703
Create Date: 2024-12-24 09:20:46.998083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc9a477bd9d'
down_revision: Union[str, None] = '80d4c5eb5703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_appointments_doctor_username_doctors_doctor_username', 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'doctor_username')
    op.drop_constraint('fk_medical_records_doctor_username_doctors_doctor_username', 'medical_records', type_='foreignkey')
    op.drop_column('medical_records', 'doctor_username')
    op.drop_constraint('fk_prescriptions_doctor_username_doctors_doctor_username', 'prescriptions', type_='foreignkey')
    op.drop_column('prescriptions', 'doctor_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescriptions', sa.Column('doctor_username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_prescriptions_doctor_username_doctors_doctor_username', 'prescriptions', 'doctors', ['doctor_username'], ['doctor_username'], ondelete='CASCADE')
    op.add_column('medical_records', sa.Column('doctor_username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_medical_records_doctor_username_doctors_doctor_username', 'medical_records', 'doctors', ['doctor_username'], ['doctor_username'], ondelete='CASCADE')
    op.add_column('appointments', sa.Column('doctor_username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_appointments_doctor_username_doctors_doctor_username', 'appointments', 'doctors', ['doctor_username'], ['doctor_username'], ondelete='CASCADE')
    # ### end Alembic commands ###
